export enum PaintsColors {
  AbaddonBlack = '#231F20',
  AdministratumGrey = '#949B94',
  AgraxEarthshade = '#5A543C',
  AgrellanBadland = '#A17359',
  AgrellanEarth = '#92816D',
  AhrimanBlue = '#00A5B9',
  AlaitocBlue = '#295788',
  AltdorfGuardBlue = '#1F56A8',
  ArmageddonDunes = '#FCAF09',
  ArmageddonDust = '#CBAD0D',
  AstorathRed = '#962F28',
  Astrogranite = '#787878',
  AstrograniteDebris = '#77726E',
  AthonianCamoshade = '#798C3D',
  AuricArmourGold = '#E9C278',
  AverlandSunset = '#FCB825',
  BaharrothBlue = '#78C4C7',
  BalorBrown = '#8B5910',
  BalthasarGold = '#87542F',
  BanebladeBrown = '#927F6E',
  BestigorFlesh = '#D28B57',
  BielTanGreen = '#479259',
  BlackfireEarth = '#F8902F',
  BloodForTheBloodGod = '#581011',
  Bloodletter = '#CB2924',
  BlueHorror = '#A2BAD2',
  BrassScorpion = '#B7895F',
  BugmansGlow = '#845045',
  CadianFleshtone = '#C87958',
  CaledorSky = '#396F9E',
  CalgarBlue = '#4273B8',
  CalibanGreen = '#00401E',
  CarroburgCrimson = '#9A4073',
  CasandoraYellow = '#F1CB4E',
  CastellanGreen = '#304921',
  CelestraGrey = '#90A8A8',
  CeramiteWhite = '#FFFFFF',
  ChangelingPink = '#F4AFCE',
  ChaosBlack = '#000000',
  ChronusBlue = '#6E97CF',
  CoeliaGreenshade = '#4A7F79',
  CoraxWhite = '#FFFFFF',
  DaemonetteHide = '#696685',
  DarkReaper = '#3C5051',
  Dawnstone = '#70756E',
  DeathGuardGreen = '#9C9171',
  DeathclawBrown = '#B36853',
  DeathworldForest = '#5D6732',
  DechalaLilac = '#B59ECC',
  DeepkinFlesh = '#D2D4C7',
  DoombullBrown = '#5D000A',
  DornYellow = '#E3D28C',
  DrakenhofNightshade = '#3B5997',
  DryadBark = '#34312C',
  DruchiiViolet = '#6A397B',
  EldarFlesh = '#EDC184',
  ElysianGreen = '#758E3A',
  EmperorsChildren = '#B94278',
  EshinGrey = '#4A4F53',
  EtheriumBlue = '#A1B9D1',
  EvilSunzScarlet = '#C21920',
  TheFang = '#436276',
  FenrisianGrey = '#709CB7',
  FireDragonBright = '#F58651',
  FlashGitzYellow = '#FFF200',
  FlayedOneFlesh = '#CBB48B',
  FueganOrange = '#AD6E38',
  FulgrimPink = '#F4AFCC',
  FulguriteCopper = '#BA8F6D',
  GaussBlasterGreen = '#84C2A9',
  GehennaGold = '#D49761',
  GenestealerPurple = '#7761AA',
  GoldenGriffon = '#C6B791',
  GolgfagBrown = '#8B5435',
  GorthorBrown = '#654641',
  GuillimanBlue = '#2E83C6',
  HashutCopper = '#C69169',
  HellionGreen = '#83C3A9',
  HexosPalesun = '#F1DCA3',
  HexwraithFlame = '#00AA5C',
  HoethBlue = '#4C7FB4',
  ImrikBlue = '#4F8DBE',
  IncubiDarkness = '#0B4849',
  Ironbreaker = '#94999D',
  JokaeroOrange = '#EE3823',
  KabaliteGreen = '#028D66',
  KantorBlue = '#002051',
  KarakStone = '#BB9662',
  KhorneRed = '#6A0002',
  Kindleflame = '#EFB494',
  KislevFlesh = '#D6A876',
  KriegKhaki = '#B7AD78',
  LamentersYellow = '#FBF44C',
  Leadbelcher = '#475659',
  LiberatorGold = '#D5C4AA',
  LongbeardGrey = '#B4AEAE',
  LorenForest = '#51702D',
  LothernBlue = '#33A2CF',
  LuciusLilac = '#B69FCB',
  LugganathOrange = '#F89E86',
  LustrianUndergrowth = '#709811',
  MacraggeBlue = '#0D407F',
  MartianIroncrust = '#F5945D',
  MartianIronearth = '#935442',
  MechanicusStandardGrey = '#3D4B4E',
  MephistonRed = '#991115',
  MootGreen = '#52B246',
  MournfangBrown = '#650A09',
  NaggarothNight = '#3E3355',
  NecronCompound = '#B1B5B8',
  NibletGreen = '#648B32',
  NighthauntGloom = '#798D96',
  NihilakhOxide = '#85B59D',
  NulnOil = '#151203',
  NurglesRot = '#9D8C30',
  NurglingGreen = '#849B63',
  OgrynCamo = '#9EA94B',
  PallidWychFlesh = '#CDCEBE',
  PinkHorror = '#91305D',
  PraxetiWhite = '#FFFFFF',
  RakarthFlesh = '#A29E92',
  RatskinFlesh = '#AE6B4E',
  ReiklandFleshshade = '#A34529',
  RelictorGold = '#E8C88D',
  RetributorArmour = '#CEAE65',
  RhinoxHide = '#493335',
  RunefangSteel = '#C6CBD0',
  RunelordBrass = '#BCAFA0',
  RussGrey = '#547588',
  RyzaRust = '#CE6426',
  ScreamerPink = '#7C1645',
  ScreamingBell = '#B3562B',
  ScreamingSkull = '#D4D3A3',
  SeraphimSepia = '#BF793E',
  Sigmarite = '#DAC38D',
  SkarsnikGreen = '#5F936F',
  SkavenblightDinge = '#48413B',
  SkinkBlue = '#59C1CE',
  SkragBrown = '#904A0F',
  SkullcrusherBrass = '#E9C58B',
  SlaaneshGrey = '#8E8C97',
  SotekGreen = '#0C6A74',
  SoulstoneBlue = '#294C86',
  SpiritstoneRed = '#FD5D3D',
  SquigOrange = '#A94F44',
  SteelLegionDrab = '#5F5134',
  StirlandBattlemire = '#321905',
  StirlandMud = '#473300',
  StegadonScaleGreen = '#074864',
  Stormfang = '#7188AA',
  StormhostSilver = '#D1D2D4',
  StormverminFur = '#736C66',
  StrakenGreen = '#628026',
  SybariteGreen = '#30A66C',
  SycoraxBronze = '#CBB394',
  SylvanethBark = '#5A5140',
  TallarnSand = '#A67610',
  TauLightOchre = '#BF6E1D',
  TeclisBlue = '#317FC1',
  TempleGuardBlue = '#329B8D',
  TerminatusStone = '#BDAA9B',
  ThousandSonsBlue = '#18ABCC',
  ThunderhawkBlue = '#417175',
  TrollSlayerOrange = '#F46C2E',
  TuskgorFur = '#883736',
  TyphusCorrosion = '#453F31',
  TyrantSkull = '#C6AF8B',
  UlthuanGrey = '#C7E0DA',
  UnderhiveAsh = '#BFBD80',
  UngorFlesh = '#D7A767',
  UshabtiBone = '#BCBC80',
  ValhallanBlizzard = '#FDF9EE',
  VerminlordHide = '#773A37',
  WaaaghFlesh = '#20552B',
  WarbossGreen = '#3E7F5D',
  WarpfiendGrey = '#6C6A75',
  WarplockBronze = '#695154',
  WarpstoneGlow = '#1E7332',
  WaystoneGreen = '#018675',
  WaywatcherGreen = '#78B04B',
  WazdakkaRed = '#8C0A0C',
  WhiteScar = '#FFFFFF',
  WildRiderRed = '#EB2E28',
  WrackWhite = '#DEDAD9',
  XereusPurple = '#471F5E',
  XV88 = '#72481E',
  YrielYellow = '#FFDB01',
  ZamesiDesert = '#DCA026',
  ZandriDust = '#9E915C',
}

export enum FactionColors {
  AgentsOfTheImperium = PaintsColors.AhrimanBlue,
  AstraMilitarum = PaintsColors.CastellanGreen,
  GenestealerCults = PaintsColors.GenestealerPurple,
  Necrons = PaintsColors.NecronCompound,
  Aeldari = PaintsColors.BielTanGreen,
  AdeptusTitanicus = PaintsColors.MechanicusStandardGrey,
  Orks = PaintsColors.WaaaghFlesh,
  UnalignedForces = PaintsColors.ChaosBlack,
  GreyKnights = PaintsColors.StormhostSilver,
  TauEmpire = PaintsColors.TauLightOchre,
  LeaguesOfVotann = PaintsColors.HexosPalesun,
  AdeptusMechanicus = PaintsColors.MephistonRed,
  ThousandSons = PaintsColors.ThousandSonsBlue,
  DeathGuard = PaintsColors.DeathGuardGreen,
  WorldEaters = PaintsColors.KhorneRed,
  ChaosKnights = PaintsColors.AbaddonBlack,
  ChaosDaemons = PaintsColors.PinkHorror,
  ImperialKnights = PaintsColors.RyzaRust,
  SpaceMarines = PaintsColors.MacraggeBlue,
  Tyranids = PaintsColors.GenestealerPurple,
  AdeptusCustodes = PaintsColors.RetributorArmour,
  AdeptaSororitas = PaintsColors.PraxetiWhite,
  ChaosSpaceMarines = PaintsColors.ChaosBlack,
  Drukhari = PaintsColors.DruchiiViolet,
}

export const factionColorMap: Record<string, FactionColors> = {
  AoI: FactionColors.AgentsOfTheImperium,
  AM: FactionColors.AdeptusMechanicus,
  GC: FactionColors.GenestealerCults,
  NEC: FactionColors.Necrons,
  AE: FactionColors.Aeldari,
  TL: FactionColors.AdeptusTitanicus,
  ORK: FactionColors.Orks,
  UN: FactionColors.UnalignedForces,
  GK: FactionColors.GreyKnights,
  TAU: FactionColors.TauEmpire,
  LoV: FactionColors.LeaguesOfVotann,
  AdM: FactionColors.AdeptusMechanicus,
  TS: FactionColors.ThousandSons,
  DG: FactionColors.DeathGuard,
  WE: FactionColors.WorldEaters,
  QT: FactionColors.ChaosKnights,
  CD: FactionColors.ChaosDaemons,
  QI: FactionColors.ImperialKnights,
  SM: FactionColors.SpaceMarines,
  TYR: FactionColors.Tyranids,
  AC: FactionColors.AdeptusCustodes,
  AS: FactionColors.AdeptaSororitas,
  CSM: FactionColors.ChaosSpaceMarines,
  DRU: FactionColors.Drukhari,
};

export const determineFactionColor = (
  factionId: string | undefined
): FactionColors => {
  if (!factionId) {
    return FactionColors.UnalignedForces;
  }

  return factionColorMap[factionId] || FactionColors.UnalignedForces;
};
